[package]
name = "background"
version = "0.1.0"
authors = ["Philipp Hoenisch <philipp@hoenisch.at>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4"
wasm-bindgen = "0.2.70"
wasm-logger = "0.2"

[dependencies.web-sys]
version = "0.3.47"
features = []