[package]
name = "wasm-bindgen-extension"
version = "0.1.0"
authors = [ "Philipp Hoenisch <philipp@hoenisch.at>" ]
edition = "2018"

[dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"
web-sys = "0.3"
